spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:develop}
  application:
    name: consultation-consumer
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        type: trace
        use_sql_comments: true
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_SCHEMA:consultation-db}
    username: ${BD_USER:postgres}
    password: ${BD_PASS:root}
    hikari:
      maximum-pool-size: 30
      connection-timeout: 24000
      minimum-idle: 10
    driver-class-name: org.postgresql.Driver

  kafka:
    consumer:
      consultation:
        topic: "consultation.service.request.topic.scheduling"
        groupId: "consultation.service-scheduling-consumer-1"

server:
  port: ${APP_PORT:8081}

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO